// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyRSJmpGAbuzPRm6gzo3kBtlGeVqyQXeA',
    appId: '1:446041018786:web:300db2de2bb0ea8bc122fb',
    messagingSenderId: '446041018786',
    projectId: 'dumy-ce60a',
    authDomain: 'dumy-ce60a.firebaseapp.com',
    storageBucket: 'dumy-ce60a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgjU2_4XQjPptWXeQfntwr4gWDO0_E_A',
    appId: '1:446041018786:android:444de277a6ee2e9dc122fb',
    messagingSenderId: '446041018786',
    projectId: 'dumy-ce60a',
    storageBucket: 'dumy-ce60a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOIgkCQ7c81TusRaXrcIfNkAXpYbnzrk',
    appId: '1:446041018786:ios:28ebff5ae69f3032c122fb',
    messagingSenderId: '446041018786',
    projectId: 'dumy-ce60a',
    storageBucket: 'dumy-ce60a.appspot.com',
    iosBundleId: 'com.example.fireBase',
  );
}
